version: '2.3'
services:
  xserver:
    image: devrt/xserver
    ipc: host
    security_opt:
    - seccomp:unconfined
    ports:
    - "3000:80"
    healthcheck:
      test: ["CMD-SHELL", "test -e /tmp/.X11-unix/X0"]
      interval: "1s"
      retries: 20
  simulator:
    image: devrt/simulator-empty
    ipc: host
    security_opt:
    - seccomp:unconfined
    environment:
    - DISPLAY=:0
    volumes_from:
    - xserver
    depends_on:
    - xserver
  workspace:
    # env_file:
    #   - .env
    #build: .
    image: lagzdins/ros-web-dev:student_env
    ipc: host
    security_opt:
    - seccomp:unconfined
    ports:
    - "3001:3000" # jupyter
    - "8080:8080" # vscode
    volumes:
    ## ML: this is where you put your path to bagfiles - shared folder
    #- /home/lagzdins/bagfiles/test_docker:/bagfiles
    - workspace:/workspace
    - ~/.gitconfig:/home/developer/.gitconfig
    environment:
    - DISPLAY=:0
    - PASSWORD=password
    volumes_from:
    - xserver
    - simulator
    depends_on:
    - xserver
volumes:
  workspace:
